import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  splashContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f7f7f7",
  },
  splashLogo: {
    width: 450,
    height: 250,
    marginBottom: 20,
    resizeMode: "contain",
  },
  splashText: {
    fontSize: 24,
    fontFamily: "Poppins_700Bold",
    color: "#ea1d2c",
    textAlign: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  container: {
    flex: 1,
    backgroundColor: "#f7f7f7",
  },
  titulo: {
    fontSize: 32,
    fontFamily: "Poppins_700Bold",
    textAlign: "center",
    marginTop: 30,
    marginBottom: 5,
    color: "#ea1d2c",
  },
  subtitulo: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: "#717171",
    textAlign: "center",
    marginBottom: 10,
    paddingHorizontal: 30,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fde9ea",
    marginHorizontal: 20,
    marginBottom: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    height: 55,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: "#3e3e3e",
    fontFamily: "Poppins_400Regular",
    fontSize: 20,
  },
  suggestionsList: {
    backgroundColor: "#fde9ea",
    marginHorizontal: 20,
    borderRadius: 15,
    marginTop: -5,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#ea1d2c",
    maxHeight: 200,
    overflow: "hidden",
    zIndex: 10,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  suggestionText: {
    color: "#3e3e3e",
    fontFamily: "Poppins_400Regular",
    fontSize: 14,
    marginLeft: 10,
  },
  sectionHeader: {
    backgroundColor: "#ffffff",
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginTop: 15,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    width: "100%",
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  cardIngrediente: {
    backgroundColor: "#ffffff",
    marginVertical: 6,
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
    overflow: "hidden",
  },
  containerImagemIngrediente: {
    width: "100%",
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  fotoIngrediente: {
    width: "100%",
    height: "100%",
    borderRadius: 15,
    resizeMode: "cover",
  },
  cardSelecionado: {
    backgroundColor: "#ea1d2c",
    borderColor: "#ea1d2c",
  },
  textoIngrediente: {
    color: "#3e3e3e",
    fontFamily: "Poppins_700Bold",
    fontSize: 12,
    textAlign: "center",
  },
  textoSelecionado: {
    color: "#ffffff",
  },
  badgeCheck: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "#ea1d2c",
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  subCategoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 15,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  subtituloTipo: {
    color: "#ea1d2c",
    fontFamily: "Poppins_700Bold",
    fontSize: 14,
    textTransform: "uppercase",
  },
  botaoMontar: {
    backgroundColor: "#ea1d2c",
    paddingVertical: 18,
    borderRadius: 25,
    marginVertical: 30,
    marginHorizontal: 20,
    alignItems: "center",
    shadowColor: "#ea1d2c",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
  },
  botaoText: {
    color: "#ffffff",
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
  },
  loadingText: {
    color: "#ffffff",
    fontSize: 16,
    fontFamily: "Poppins_400Regular",
  },
  resultadoContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 25,
    padding: 25,
    marginHorizontal: 20,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: "#ea1d2c",
  },
  nomeReceita: {
    fontSize: 24,
    fontFamily: "Poppins_700Bold",
    color: "#ea1d2c",
    marginBottom: 8,
    textAlign: "center",
  },
  descricaoText: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    fontStyle: "italic",
    color: "#717171",
    textAlign: "left",
    marginBottom: 15,
    paddingHorizontal: 10,
    lineHeight: 20,
  },
  classificacaoContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  classificacaoBadge: {
    backgroundColor: "#ea1d2c",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  classificacaoText: {
    color: "#ffffff",
    fontSize: 10,
    fontFamily: "Poppins_700Bold",
    textTransform: "uppercase",
  },
  infoContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginBottom: 20,
  },
  infoPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(234, 29, 44, 0.1)",
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(234, 29, 44, 0.3)",
  },
  infoText: {
    color: "#ea1d2c",
    fontSize: 12,
    fontFamily: "Poppins_700Bold",
    marginLeft: 5,
  },
  ingredientesTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
    marginTop: 10,
    marginBottom: 10,
  },
  ingredienteItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingLeft: 5,
  },
  ingredienteBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ea1d2c",
    marginRight: 10,
  },
  ingredienteTexto: {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#717171",
    flex: 1,
  },
  ingredienteQuantidade: {
    fontSize: 14,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
  },
  faltandoText: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: "#ea1d2c",
    marginBottom: 15,
    textAlign: "center",
    backgroundColor: "rgba(234, 29, 44, 0.1)",
    padding: 10,
    borderRadius: 10,
  },
  preparoTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
    marginTop: 15,
  },
  preparoText: {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#717171",
    lineHeight: 22,
  },
  passoItem: {
    flexDirection: "row",
    marginBottom: 12,
  },
  passoNumeroContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ea1d2c",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
  },
  passoNumero: {
    color: "#ffffff",
    fontSize: 12,
    fontFamily: "Poppins_700Bold",
  },
  passoTexto: {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#717171",
    flex: 1,
    lineHeight: 22,
  },
  dicaText: {
    fontSize: 14,
    fontStyle: "italic",
    fontFamily: "Poppins_400Regular",
    color: "#ea1d2c",
    marginTop: 10,
    backgroundColor: "rgba(234, 29, 44, 0.05)",
    padding: 10,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#ea1d2c",
  },
  beneficioTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
    marginTop: 15,
  },
  beneficioText: {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#717171",
    lineHeight: 22,
  },
  containerBotoesPosRefeicao: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 25,
    gap: 12,
  },
  botaoAcaoPos: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 15,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  botaoTentarOutra: {
    backgroundColor: "#ea1d2c",
  },
  botaoMudarTudo: {
    backgroundColor: "#4caf50",
    borderWidth: 0,
  },
  botaoTextPequeno: {
    color: "#ffffff",
    fontSize: 14,
    fontFamily: "Poppins_700Bold",
  },
  selectedTitle: {
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
    color: "#ea1d2c",
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 5,
  },
  selectedChipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    marginBottom: 10,
    gap: 8,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(234, 29, 44, 0.1)",
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(234, 29, 44, 0.5)",
  },
  chipText: {
    color: "#3e3e3e",
    fontFamily: "Poppins_400Regular",
    fontSize: 13,
  },
  nutricionalContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#f9f9f9",
    borderRadius: 15,
    padding: 15,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  nutricionalItem: {
    alignItems: "center",
    flex: 1,
  },
  nutricionalValor: {
    color: "#3e3e3e",
    fontFamily: "Poppins_700Bold",
    fontSize: 14,
  },
  nutricionalLabel: {
    color: "#717171",
    fontFamily: "Poppins_400Regular",
    fontSize: 10,
    textTransform: "uppercase",
    marginTop: 2,
  },
  substituicaoTitle: {
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
    marginTop: 20,
    marginBottom: 10,
  },
  substituicaoItem: {
    backgroundColor: "#f9f9f9",
    padding: 10,
    borderRadius: 10,
    marginBottom: 6,
    borderLeftWidth: 2,
    borderLeftColor: "#ea1d2c",
  },
  substituicaoText: {
    color: "#717171",
    fontSize: 13,
    fontFamily: "Poppins_400Regular",
  },
  typeSelectorContainer: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    marginHorizontal: 20,
    borderRadius: 15,
    padding: 5,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  typeOption: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 12,
  },
  typeOptionSelected: {
    backgroundColor: "#ea1d2c",
  },
  typeText: {
    color: "#717171",
    fontFamily: "Poppins_700Bold",
    fontSize: 12,
  },
  typeLabel: {
    fontSize: 14,
    fontFamily: "Poppins_700Bold",
    color: "#3e3e3e",
    marginLeft: 25,
    marginBottom: 8,
    marginTop: 20,
  },
  // NOVOS ESTILOS DE INTEGRAÇÃO
  userStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginHorizontal: 20,
    marginTop: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  userEmailText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#3e3e3e',
    flex: 1,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(234, 29, 44, 0.1)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  logoutButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 12,
    color: '#ea1d2c',
    marginLeft: 4,
  },
  loginHintText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#717171',
    flex: 1,
  },
  loginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ea1d2c',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  loginButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 12,
    color: '#ffffff',
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
    backgroundColor: '#ffffff',
    borderRadius: 25,
    padding: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 22,
    gap: 6,
  },
  tabButtonActive: {
    backgroundColor: '#ea1d2c',
  },
  tabButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 13,
    color: '#ea1d2c',
  },
  tabButtonTextActive: {
    color: '#ffffff',
  },
  botaoSalvarGrande: {
    backgroundColor: '#4caf50',
    paddingVertical: 15,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 12,
    shadowColor: '#4caf50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  tituloSecao: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: "#ea1d2c",
    marginBottom: 15,
    marginTop: 10,
  },
  emptySavedContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    padding: 20,
  },
  emptySavedText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#717171',
    marginTop: 15,
  },
  emptySavedSubtext: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#9E9E9E',
    textAlign: 'center',
    marginTop: 5,
    lineHeight: 18,
  },
  savedCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  savedCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  savedCardTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#3e3e3e',
    flex: 1,
    marginRight: 10,
  },
  savedCardDesc: {
    fontFamily: 'Poppins_400Regular',
    fontStyle: 'italic',
    fontSize: 12,
    color: '#717171',
    marginBottom: 10,
  },
  savedCardFooter: {
    flexDirection: 'row',
    gap: 8,
  },
  savedCardPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(234, 29, 44, 0.05)',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  savedCardPillText: {
    color: '#ea1d2c',
    fontSize: 10,
    fontFamily: 'Poppins_700Bold',
    marginLeft: 3,
  },
  modalSavedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  btnVoltarModal: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
  },
  btnVoltarText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#3e3e3e',
    marginLeft: 5,
  },
  btnExcluirModal: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#FFEBEE',
  },
});
